### ISSUE TITLE
[Policy] 지역구별 혜택 출력 페이지 개발

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#16]
## 📄 설명
DataBase에 저장된 정보를 활용할 수 있도록, 사용자가 지역구를 검색 했을 때 출력할 화면단을 개발

## 🗓️ TO-DO
- [x] 템플릿 엔진인 JSP를 활용하여 레이아웃 구성
- [x] 화면 디자인(CSS - 필요시 부트스트랩 컴포넌트 사용)
- [x] 동적 처리(JS - 지역구 마우스 이벤트 등)

## ➕ ETC
- UI 화면은 설계한 Figma를 참조하며, 디자인적으로 개선되면 좋을 부분은 팀원들과 커뮤니케이션
