### ISSUE TITLE
[Member] 마이페이지 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#22]
## 📄 설명
회원 로그인 이후, 자신의 정보를 수정하거나 확인할 수 있는 마이페이지 화면 레이아웃을 구성

## 🗓️ TO-DO
- [x] 마이페이지 레이아웃 구현
- [x] 헤더에서 마이페이지로 페이지 전환 할 수 있는 모달 창 구현
- [x] 페이지 전환 연결
