### ISSUE TITLE
[Interest] 관심사 등록(회원 가입시 등록)  기능 개발

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#26]
## 📄 설명
회원 관심사 연결을 위해 관심사 객체를 생성하고 관련된 서버 기능을 개발

## 🗓️ TO-DO
- [x] Interest 도메인 구조 설정
- [x] Interest 객체 생성
- [x] MyBatis 객체 Mapping
- [x] 회원 가입 기능 개발
- [x] 관심사 생성(C) 기능 개발
