### ISSUE TITLE
[Policy] 혜택 상세 정보 조회 기능 개발

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#28]
## 📄 설명
헤택에 대한 상세 정보를 사용자에게 보여주는 상세 페이지를 개발합니다. (서버, 클라이언트 동시 진행)
<br>
<img width="374" alt="image" src="https://github.com/user-attachments/assets/fa775319-3be4-4a0b-959c-8b55219df614">

## 🗓️ TO-DO
- [ ] 화면 레이아웃을 구성(JSP)
- [ ] 서버 시스템 개발 (필요시 RestfulAPI) + 찜
- [ ] JS로 동적 이벤트 처리 및 CSS 디자인 구성

## ➕ ETC
- 추석 연휴간 개인적으로 분담한 작업 단위입니다.
- 본인이 개발을 진행하면서 작업 단위가 변경될 수 있으니, TO-DO는 본인에게 맞게 수정이 필요하면 수정하시면 됩니다.
