### ISSUE TITLE
[Docs] 프로젝트 문서화

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#3]
## 📄 설명
"살구" 프로젝트에 사용될 기획 및 분석 작업 입니다.

## 🗓️ TO-DO
- [x] 기능 명세 - 와이어 프레임을 참고하여 설계
- [x] ERD - 기능과 데이터 관계 설계
- [x] 와이어 프레임 - 프로젝트 화면 디자인으로 기능을 고려하여 설계

## ➕ ETC
- 기능 명세 활용 Tool: `Notion`
- ERD: 활용 Tool: `ERD Cloud` 또는 `Notion + dbdiagram.io`
- 와이어 프레임 활용 Tool :  `Figma`

**Comment by IToriginal** [comment]
## ☑️ 기능 명세 - 와이어 프레임을 참고하여 설계
- v1 기능 명세 작성 완료 (Notion)

## ☑️  ERD - 기능과 데이터 관계 설계
- v1 ERD 작성 완료 (ERD Cloud)

## ☑️  ERD - 기능과 데이터 관계 설계
- v1 와이어 프레임 작성 완료 (Figma)
 
## 🚀 Check this issue
- 프로젝트 진행에 문제는 없어 보이며, 개발을 진행하며 문제점을 찾게 되면 변경될 가능성도 있음. (지속적으로 분석 예정)
- 예상 필요 기능 작성은 완료하였고, 추후 프로젝트 기간에 여유가 있다면 추가적인 기능 명세 및 ERD, UI설계를 진행할 예정.
- @ssoulistic 
- @smuhsh 
- @hwangheejung
