### ISSUE TITLE
[Global] 객체간 관계 점검

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#35]
## 📄 설명
DataBase에 연결괸 테이블 관계와 자바 프로그램에서 객체간의 관계를 점검하고자 합니다.

## 🗓️ TO-DO
- [x] Member 객체 점검
- [x] Interest 객체 점검
- [x] Category 객체 생성
- [x] MyBatis Join 쿼리 테스트: 마이페이지 정보 가져오기

## ➕ ETC
마이페이지 API 개발 진행 중 마이바티스로 1:N관계의 조인 쿼리가 어플리케이션 객체에 매핑이 제대로 동작 되지 않고 있습니다.
때문에 해당 이유를 찾고자 모든 객체를 점검하고, 해당 내용을 해결하고자 이슈를 생성하였습니다.
아래는 지속적으로 발생하는 에러 로그입니다. 참고 바랍니다.
```
2024-09-15T18:34:11.478+09:00 DEBUG 74017 --- [apricot] [nio-8080-exec-3] o.s.web.servlet.DispatcherServlet        : Failed to complete request: org.mybatis.spring.MyBatisSystemException
2024-09-15T18:34:11.479+09:00 ERROR 74017 --- [apricot] [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.mybatis.spring.MyBatisSystemException] with root cause
```
