### ISSUE TITLE
[Scrap] 찜 기능 개발 

### ISSUE THREAD

**Issue by hwangheejung** [Team-Apricot/apricot-application#39]
## 📄 설명
회원은 혜택 리스트에서 관심 있는 혜택을 선택해서 저장할 수 있다.
저장된 혜택은 마이페이지를 통해 확인할 수 있다.

## 🗓️ TO-DO
- [x] Oracle 테이블 생성
- [x] Scrap VO, DAO 생성
- [x] MyBatis 쿼리 구현
- [x] 동작 확인: PostMan을 통해 API를 처리하고 저장된 정보를 마이페이지에서 불러와지는지 확인

## ➕ ETC
상세페이지 개발과 별도 진행하므로 RestAPI를 개발하여 ajax 통신
