### ISSUE TITLE
[Policy] 워드 클라우드 - 지역구별 혜택 수 구현(Redis 도입)

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#48]
## 📄 설명
지역구 별 혜택수를 count하는 SQL 쿼리를 이용해서 워드 클라우드에 업데이트 하는 로직을 개발합니다.
다만, 매번 메인 페이지를 호출하면서 쿼리를 호출하는 것은 비효율적이라 판단되므로 조회 처리를 고민해보겠습니다.

## 🗓️ TO-DO
- [x] 지역구별 혜택수 SQL 쿼리 개발
- [x] RestAPI(`@GetMapping`) 개발: wordCloud.js 페이지에서 ajax 호출하여 사용 예정
- [x] NoSQL 사용 고려: Redis 기술 점검
- [x] RDB -> NoSQL 구현
- [x] 혜택수 랭킹 구현

**Comment by IToriginal** [comment]
## `Redis` 도입
- 현재 워드 클라우드 조회 시, RDBMS인 ORACLE을 사용하여 매번 메인 페이지 호출 때마다 쿼리가 실행되고 있습니다. 
- 이 방식은 반복적인 데이터 조회로 인해 성능 저하와 비효율을 초래합니다. (Main Page 접속마다 쿼리 실행)
- 특히, 워드 클라우드는 조회 빈도가 높고, 데이터 변경은 하루에 한 번 이루어지면 된다고 생각되어, 실시간으로 데이터를 갱신할 필요가 없습니다. 
- 이러한 특성에 따라, 조회 성능을 개선하고 시스템 리소스를 효율적으로 활용하기 위해 Redis를 도입하여 캐싱하는 것이 적합하다고 판단됩니다. 
- Redis를 도입하면 일정 기간 동안 캐싱된 데이터를 제공함으로써 불필요한 RDBMS인 오라클 클라우드 데이터베이스 호출을 줄이고 시스템 성능을 최적화할 수 있을 것으로  기대됩니다.
- 지역구별 혜택 조회에도 활용가능할 것으로 예상됩니다.(확장성)

### 도입시 필요한 개발 환경 세팅
- 개발중인 로컬 컴퓨터에 Redis를 설치해야 합니다.

[Docker에 Redis 설치 - macOS]
```
$ docker network ls
$ docker network create redis-net
$ docker pull redis
$ docker run --name redis-server -p 6379:6379 --network redis-net -d redis redis-server --appendonly yes
$ docker run -it --network redis-net --rm redis redis-cli -h redis-server

<<< set key value
>>> OK
<<< get key
>>> "value"
```
