### ISSUE TITLE
[Member] 지역구 추천 알고리즘 검토 

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#49]
## 📄 설명
회원들에게 지역구 추천은 어떻게 진행해야 할지 알고리즘 해결 방법으로 고민하고 해당 내용을 공유합니다.

## 🗓️ TO-DO
- [x] 추천 알고리즘 스터디
- [x] 추천 시나리오 구성
- [x] 팀원 내용 공유

## ➕ ETC
회의를 통해 정해진 내용
### 1️⃣ 추천에 사용될 그룹은 연령, 성별, 결혼상태를 묶어 그룹화한다.
- 예: '20대 남성 기혼'

### 2️⃣ 더미데이터 생성
- AOP 기능은 시간상의 이유로 고려하지 않고 AOP를 통해 얻어진 로그를 카운트했다는 가정하에 더미 테이블을 만들어서 진행한다.
