### ISSUE TITLE
[Review] 살구 서비스 최종 점검 

### ISSUE THREAD

**Issue by IToriginal** [Team-Apricot/apricot-application#56]
## 📄 설명
살구 서비스 최종 점검

## 🗓️ TO-DO
- [x] 서비스 점검
  - [x] Main Page
  - [x] Login
  - [x] 회원 가입 기능
  - [x] 비밀번호 찾기 기능 - 미구현
  - [x] MyPage
  - [x] 수정 기능
  - [x] 비밀번호 변경 기능
  - [x] 탈퇴 기능 - 미구현
  - [x] 검색 기능
  - [x] **[핵심] 추천 기능**
  - [x] **[핵심] 지역구별 혜택 조회 기능(필터 처리)**
  - [x] **[핵심]혜택 상세 조회 기능**
  - [x] 찜 기능
- [x] 기술 문서 최신화
- [x] PPT 자료 만들기

## ➕ ETC
고생하셨습니다. 👍🏻
